import os, time, random, logging, requests, threading
from datetime import datetime, timedelta
from http.server import HTTPServer, BaseHTTPRequestHandler
from dotenv import load_dotenv
import telebot
from telebot import types

load_dotenv()

# ================= CONFIG =================
API_TOKEN = os.getenv("BOT_TOKEN")
if not API_TOKEN:
    print("❌ BOT_TOKEN topilmadi!")
    exit(1)

ADMIN_ID = int(os.getenv("ADMIN_ID", "2010030869"))
BOT_USERNAME = os.getenv("BOT_USERNAME", "stars_sovga_gifbot")
if BOT_USERNAME.startswith("@"):
    BOT_USERNAME = BOT_USERNAME[1:]

ADMIN_USERNAME = os.getenv("ADMIN_USERNAME", "@Stars_5_odam_1stars")
DAILY_BONUS = 0.20
TASK_REWARD = 0.20

# PostgreSQL URL (agar mavjud bo'lsa)
DATABASE_URL = os.getenv("DATABASE_URL")
DB_TYPE = "postgres" if DATABASE_URL else "sqlite"

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger("BOT")

lock = threading.Lock()

# ================= DATABASE =================
if DB_TYPE == "postgres":
    import psycopg2
    import psycopg2.extensions

class DB:
    def __init__(self):
        if DB_TYPE == "postgres":
            self.conn = psycopg2.connect(DATABASE_URL)
            self.cur = self.conn.cursor()
        else:
            self.conn = __import__('sqlite3').connect("/tmp/bot.db", check_same_thread=False)
            self.cur = self.conn.cursor()
        self.init()

    def _execute(self, query, params=None, fetch=None):
        with lock:
            if DB_TYPE == "postgres":
                # replace ? with %s
                query = query.replace("?", "%s")
                # SERIAL ni INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ga aylantirish kerak emas, chunki jadval yaratilishda to‘g‘ri ishlatilgan.
                # Lekin oddiy query uchun bu yetarli.
                self.cur.execute(query, params or ())
                if fetch == "one":
                    return self.cur.fetchone()
                elif fetch == "all":
                    return self.cur.fetchall()
                self.conn.commit()
            else:
                self.cur.execute(query, params or ())
                if fetch == "one":
                    return self.cur.fetchone()
                elif fetch == "all":
                    return self.cur.fetchall()
                self.conn.commit()

    def init(self):
        # Barcha jadvallarni yaratish
        self._execute("""
        CREATE TABLE IF NOT EXISTS users (
            user_id BIGINT PRIMARY KEY,
            username TEXT,
            first_name TEXT,
            successful_invites INTEGER DEFAULT 0,
            stars REAL DEFAULT 0,
            vip INTEGER DEFAULT 0,
            is_banned INTEGER DEFAULT 0,
            last_daily TIMESTAMP,
            daily_streak INTEGER DEFAULT 0,
            total_spent REAL DEFAULT 0,
            total_earned REAL DEFAULT 0
        );
        """)
        self._execute("""
        CREATE TABLE IF NOT EXISTS invite_history (
            id SERIAL PRIMARY KEY,
            inviter_id BIGINT,
            invited_id BIGINT,
            invited_name TEXT,
            source TEXT DEFAULT 'link',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        """)
        self._execute("""
        CREATE TABLE IF NOT EXISTS forced_channels (
            id SERIAL PRIMARY KEY,
            channel_type TEXT DEFAULT 'telegram',
            channel_id BIGINT,
            channel_username TEXT,
            channel_name TEXT,
            channel_url TEXT
        );
        """)
        self._execute("""
        CREATE TABLE IF NOT EXISTS user_forced (
            user_id BIGINT,
            channel_id INTEGER,
            completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (user_id, channel_id)
        );
        """)
        self._execute("""
        CREATE TABLE IF NOT EXISTS tasks (
            id SERIAL PRIMARY KEY,
            task_type TEXT DEFAULT 'telegram',
            channel_id BIGINT,
            channel_username TEXT,
            channel_name TEXT,
            channel_url TEXT,
            reward REAL DEFAULT 0.20
        );
        """)
        self._execute("""
        CREATE TABLE IF NOT EXISTS user_tasks (
            user_id BIGINT,
            task_id INTEGER,
            completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PRIMARY KEY (user_id, task_id)
        );
        """)
        self._execute("""
        CREATE TABLE IF NOT EXISTS pending_referrals (
            invited_id BIGINT PRIMARY KEY,
            inviter_id BIGINT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        """)
        self._execute("""
        CREATE TABLE IF NOT EXISTS purchase_history (
            id SERIAL PRIMARY KEY,
            user_id BIGINT,
            item_name TEXT,
            item_emoji TEXT,
            price REAL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        """)

    # ---------- Foydalanuvchi ----------
    def create_user(self, uid, username, name):
        self._execute("INSERT INTO users (user_id, username, first_name) VALUES (?,?,?) ON CONFLICT (user_id) DO NOTHING", (uid, username, name))

    def get(self, uid):
        row = self._execute("SELECT successful_invites, stars, vip, total_spent, last_daily, daily_streak, total_earned FROM users WHERE user_id=?", (uid,), fetch="one")
        if row:
            return {"successful_invites": row[0] or 0, "stars": float(row[1] or 0), "vip": row[2] or 0, "spent": float(row[3] or 0), "last_daily": row[4], "streak": row[5] or 0, "earned": float(row[6] or 0)}
        return {"successful_invites": 0, "stars": 0.0, "vip": 0, "spent": 0.0, "last_daily": None, "streak": 0, "earned": 0.0}

    # ---------- Referal ----------
    def add_pending_referral(self, invited_id, inviter_id):
        self._execute("INSERT INTO pending_referrals (invited_id, inviter_id) VALUES (?,?) ON CONFLICT (invited_id) DO UPDATE SET inviter_id=?", (invited_id, inviter_id, inviter_id))

    def get_pending_inviter(self, invited_id):
        row = self._execute("SELECT inviter_id FROM pending_referrals WHERE invited_id=?", (invited_id,), fetch="one")
        return row[0] if row else None

    def remove_pending(self, invited_id):
        self._execute("DELETE FROM pending_referrals WHERE invited_id=?", (invited_id,))

    def add_history(self, inviter_id, invited_id, invited_name, source="link"):
        self._execute("INSERT INTO invite_history (inviter_id, invited_id, invited_name, source) VALUES (?,?,?,?)", (inviter_id, invited_id, invited_name, source))

    def check_duplicate(self, inviter_id, invited_id):
        row = self._execute("SELECT COUNT(*) FROM invite_history WHERE inviter_id=? AND invited_id=?", (inviter_id, invited_id), fetch="one")
        return row[0] > 0

    def add_successful_invite(self, uid):
        row = self._execute("SELECT successful_invites, stars, total_earned FROM users WHERE user_id=?", (uid,), fetch="one")
        if row:
            old_cnt = row[0] or 0; stars = float(row[1] or 0); earned = float(row[2] or 0)
        else:
            old_cnt = 0; stars = 0.0; earned = 0.0
        new_cnt = old_cnt + 1
        added = 1.0 if (new_cnt % 2 == 0 and old_cnt % 2 != 0) else 0.0
        new_stars = stars + added
        new_earned = earned + added
        self._execute("UPDATE users SET successful_invites=?, stars=?, total_earned=? WHERE user_id=?", (new_cnt, new_stars, new_earned, uid))
        return new_cnt, new_stars

    # ---------- Yulduzlar ----------
    def sub_star(self, uid, amount):
        row = self._execute("SELECT stars FROM users WHERE user_id=?", (uid,), fetch="one")
        cur = float(row[0] or 0)
        new = max(0.0, cur - amount)
        self._execute("UPDATE users SET stars=?, total_spent=total_spent+? WHERE user_id=?", (new, amount, uid))
        return new

    def add_stars_admin(self, uid, amount):
        row = self._execute("SELECT stars FROM users WHERE user_id=?", (uid,), fetch="one")
        cur = float(row[0] or 0)
        new = cur + amount
        self._execute("UPDATE users SET stars=?, total_earned=total_earned+? WHERE user_id=?", (new, amount, uid))
        return new

    def give_daily_bonus(self, uid):
        row = self._execute("SELECT last_daily, stars, daily_streak, total_earned FROM users WHERE user_id=?", (uid,), fetch="one")
        if not row: return False, 0, 0, 0, 0
        last_daily, cs, streak, te = row
        cs = float(cs or 0); streak = streak or 0; te = float(te or 0)
        now = datetime.now()
        if last_daily:
            try:
                last = last_daily if isinstance(last_daily, datetime) else datetime.fromisoformat(str(last_daily))
                if now.date() == last.date(): return False, cs, 0, streak, 0
                streak = streak + 1 if (now.date() - last.date()).days == 1 else 1
            except: streak = 1
        else: streak = 1
        bonus = DAILY_BONUS + (0.5 if streak % 7 == 0 else 0)
        ns = cs + bonus; ne = te + bonus
        self._execute("UPDATE users SET stars=?, last_daily=?, daily_streak=?, total_earned=? WHERE user_id=?", (ns, now.isoformat(), streak, ne, uid))
        return True, ns, bonus, streak, bonus - DAILY_BONUS

    # ---------- Boshqa ----------
    def grant_vip(self, uid):
        self._execute("UPDATE users SET vip=1 WHERE user_id=?", (uid,))

    def get_top(self, limit=10):
        return self._execute("SELECT user_id, username, first_name, successful_invites, stars, vip, daily_streak FROM users WHERE is_banned=0 ORDER BY successful_invites DESC LIMIT ?", (limit,), fetch="all")

    def get_purchase_history(self, uid):
        return self._execute("SELECT item_name, item_emoji, price, created_at FROM purchase_history WHERE user_id=? ORDER BY created_at DESC LIMIT 10", (uid,), fetch="all")

    def add_purchase_history(self, uid, name, emoji, price):
        self._execute("INSERT INTO purchase_history (user_id, item_name, item_emoji, price) VALUES (?,?,?,?)", (uid, name, emoji, price))

    def check_ban(self, uid):
        row = self._execute("SELECT is_banned FROM users WHERE user_id=?", (uid,), fetch="one")
        return row and row[0] == 1

    def ban_user(self, uid):
        self._execute("UPDATE users SET is_banned=1 WHERE user_id=?", (uid,))

    def unban_user(self, uid):
        self._execute("UPDATE users SET is_banned=0 WHERE user_id=?", (uid,))

    def get_all_users_for_ad(self):
        rows = self._execute("SELECT user_id FROM users WHERE is_banned=0", fetch="all")
        return [r[0] for r in rows]

    def get_stats(self):
        users = self._execute("SELECT COUNT(*) FROM users", fetch="one")[0]
        invites = self._execute("SELECT SUM(successful_invites) FROM users", fetch="one")[0] or 0
        stars = float(self._execute("SELECT SUM(stars) FROM users", fetch="one")[0] or 0)
        vip = self._execute("SELECT COUNT(*) FROM users WHERE vip=1", fetch="one")[0]
        spent = float(self._execute("SELECT SUM(total_spent) FROM users", fetch="one")[0] or 0)
        total_invites = self._execute("SELECT COUNT(*) FROM invite_history", fetch="one")[0]
        purchases = self._execute("SELECT COUNT(*) FROM purchase_history", fetch="one")[0]
        return {"users": users, "total_invites": total_invites, "stars": stars, "vip": vip, "spent": spent, "invites": invites, "purchases": purchases}

    # ---------- Majburiy kanallar ----------
    def get_forced_channels(self):
        return self._execute("SELECT id, channel_type, channel_id, channel_username, channel_name, channel_url FROM forced_channels", fetch="all")

    def add_forced_channel(self, ctype, ch_id, uname, name, url):
        self._execute("INSERT INTO forced_channels (channel_type, channel_id, channel_username, channel_name, channel_url) VALUES (?,?,?,?,?)", (ctype, ch_id, uname, name, url))

    def remove_forced_channel(self, db_id):
        self._execute("DELETE FROM forced_channels WHERE id=?", (db_id,))

    def is_forced_completed(self, uid, db_id):
        row = self._execute("SELECT 1 FROM user_forced WHERE user_id=? AND channel_id=?", (uid, db_id), fetch="one")
        return row is not None

    def complete_forced(self, uid, db_id):
        if not self.is_forced_completed(uid, db_id):
            self._execute("INSERT INTO user_forced (user_id, channel_id) VALUES (?,?)", (uid, db_id))

    # ---------- Vazifalar ----------
    def get_tasks(self):
        return self._execute("SELECT id, task_type, channel_id, channel_username, channel_name, channel_url, reward FROM tasks", fetch="all")

    def add_task(self, ttype, ch_id, uname, name, url, reward=TASK_REWARD):
        self._execute("INSERT INTO tasks (task_type, channel_id, channel_username, channel_name, channel_url, reward) VALUES (?,?,?,?,?,?)", (ttype, ch_id, uname, name, url, reward))

    def remove_task(self, tid):
        self._execute("DELETE FROM tasks WHERE id=?", (tid,))

    def is_task_completed(self, uid, tid):
        row = self._execute("SELECT 1 FROM user_tasks WHERE user_id=? AND task_id=?", (uid, tid), fetch="one")
        return row is not None

    def complete_task(self, uid, tid, reward):
        if self.is_task_completed(uid, tid): return False
        self._execute("INSERT INTO user_tasks (user_id, task_id) VALUES (?,?)", (uid, tid))
        self._execute("UPDATE users SET stars=stars+?, total_earned=total_earned+? WHERE user_id=?", (reward, reward, uid))
        return True

    def get_user_completed_tasks(self, uid):
        rows = self._execute("SELECT task_id FROM user_tasks WHERE user_id=?", (uid,), fetch="all")
        return [r[0] for r in rows]

    # ---------- Qidiruv ----------
    def search_user(self, query):
        try:
            q = int(query)
            row = self._execute("SELECT user_id, username, first_name, successful_invites, stars, vip, daily_streak FROM users WHERE user_id=?", (q,), fetch="one")
            if row: return [row]
        except: pass
        return self._execute("SELECT user_id, username, first_name, successful_invites, stars, vip, daily_streak FROM users WHERE username LIKE ? OR first_name LIKE ? LIMIT 10", (f"%{query}%", f"%{query}%"), fetch="all")

db = DB()

# ================= SHOP =================
SHOP = {
    1: {"price":15,"name":"❤️ Pushti Yurakcha","emoji":"❤️","photo":"https://i.imgur.com/8Yp9Z2M.jpg","desc":"Chiroyli pushti yurak"},
    2: {"price":15,"name":"🧸 Ayiqcha","emoji":"🧸","photo":"https://i.imgur.com/5f2vL8K.jpg","desc":"Yoqimli ayiqcha"},
    3: {"price":25,"name":"🌹 Atirgul","emoji":"🌹","photo":"https://i.imgur.com/7zK9pQm.jpg","desc":"Romantik atirgul"},
    4: {"price":25,"name":"🎁 Sovg'a qutisi","emoji":"🎁","photo":"https://i.imgur.com/3vX9pLm.jpg","desc":"Sirli sovg'a"},
    5: {"price":50,"name":"🎂 Tort","emoji":"🎂","photo":"https://i.imgur.com/9pL2mNx.jpg","desc":"Shirin tort + VIP"},
    6: {"price":50,"name":"💐 Gullar","emoji":"💐","photo":"https://i.imgur.com/XkP5vRt.jpg","desc":"Guldasta + VIP"},
    7: {"price":100,"name":"🏆 Oltin kubok","emoji":"🏆","photo":"https://i.imgur.com/vL9pQmN.jpg","desc":"Oltin + VIP"},
    8: {"price":100,"name":"💍 Olmos uzuk","emoji":"💍","photo":"https://i.imgur.com/kP8mNxZ.jpg","desc":"Brilliant + VIP"},
    9: {"price":200,"name":"💎 Brilliant","emoji":"💎","photo":"https://i.imgur.com/kP8mNxZ.jpg","desc":"Qimmatbaho + VIP"},
    10:{"price":500,"name":"👑 Qirol toji","emoji":"👑","photo":"https://i.imgur.com/XkP5vRt.jpg","desc":"Haqiqiy toj + VIP"},
}

# ================= YORDAMCHI =================
def check_sub(uid):
    channels = db.get_forced_channels()
    not_sub = []
    for ch in channels:
        db_id, ctype, ch_id, username, name, url = ch
        if ctype == 'telegram':
            try:
                member = bot.get_chat_member(ch_id, uid)
                if member.status not in ['member','administrator','creator']:
                    not_sub.append({"db_id": db_id, "type": ctype, "name": name, "url": url, "username": username})
            except Exception as e:
                if "chat not found" in str(e).lower():
                    logger.warning(f"Kanal topilmadi, o'chirilmoqda: {db_id}")
                    db.remove_forced_channel(db_id)
                else:
                    logger.warning(f"Tekshirib bo'lmadi {db_id}: {e}")
        else:  # instagram/youtube
            if not db.is_forced_completed(uid, db_id):
                not_sub.append({"db_id": db_id, "type": ctype, "name": name, "url": url, "username": username})
    return not_sub

def add_footer(text):
    mot = random.choice(["🔥 Siz zo'rsiz!","💪 Har bir taklif - yulduz","⭐ Yulduzlar kutmoqda"])
    return f"{text}\n\n{'─'*20}\n💡 <i>{mot}</i>"

def format_stars(stars):
    if stars == int(stars): return str(int(stars))
    return f"{stars:.2f}"

def get_invite_link(uid):
    return f"https://t.me/{BOT_USERNAME}?start={uid}"

def finalize_referral(invited_id):
    inviter_id = db.get_pending_inviter(invited_id)
    if inviter_id:
        db.create_user(inviter_id, None, "User")
        try:
            user = bot.get_chat(invited_id)
            name = user.first_name
        except: name = "User"
        db.add_history(inviter_id, invited_id, name, "link")
        new_cnt, new_stars = db.add_successful_invite(inviter_id)
        db.remove_pending(invited_id)
        try:
            bot.send_message(inviter_id, f"🎉 Sizning havolangiz orqali {name} qo'shildi! Sizda {new_cnt} ta taklif, {format_stars(new_stars)}⭐")
        except: pass

# ================= BOT =================
bot = telebot.TeleBot(API_TOKEN, parse_mode="HTML", threaded=False)

@bot.message_handler(commands=["start"])
def start(m):
    uid = m.from_user.id
    try:
        if db.check_ban(uid):
            return bot.send_message(m.chat.id, "❌ Bloklangansiz!")
        if m.text and len(m.text.split()) > 1:
            param = m.text.split()[1]
            try:
                ref = int(param)
            except:
                ref = None
            if ref and ref != uid and not db.check_duplicate(ref, uid):
                db.add_pending_referral(uid, ref)
        not_sub = check_sub(uid)
        if not_sub:
            markup = types.InlineKeyboardMarkup(row_width=1)
            for ch in not_sub:
                if ch['type'] == 'telegram':
                    markup.add(types.InlineKeyboardButton(f"{ch['name']} - OBUNA", url=ch['url']))
                    markup.add(types.InlineKeyboardButton("✅ OBUNA BO'LDIM", callback_data=f"forcesub_telegram_{ch['db_id']}"))
                else:
                    markup.add(types.InlineKeyboardButton(f"{ch['name']} - HA VOLA", url=ch['url']))
                    markup.add(types.InlineKeyboardButton("✅ BAJARDIM (10 soniya)", callback_data=f"forcesub_claim_{ch['db_id']}"))
            return bot.send_message(m.chat.id, "❌ Obuna bo'ling:\n\n", reply_markup=markup)
        finalize_referral(uid)
        db.create_user(uid, m.from_user.username, m.from_user.first_name)
        u = db.get(uid)
        vip_status = "✅ HA" if u["vip"] else "❌ YO'Q"
        markup = types.InlineKeyboardMarkup(row_width=2)
        markup.add(types.InlineKeyboardButton("🛒 DO'KON", callback_data="shop"), types.InlineKeyboardButton(f"🎁 +{DAILY_BONUS}⭐", callback_data="daily"))
        markup.add(types.InlineKeyboardButton("🏆 TOP", callback_data="top"), types.InlineKeyboardButton("📊 PROFIL", callback_data="profile"))
        markup.add(types.InlineKeyboardButton("🔗 LINK", callback_data="link"), types.InlineKeyboardButton("✅ VAZIFALAR", callback_data="tasks"))
        text = f"""🌟 <b>STARS BOT</b>
👤 <b>{m.from_user.first_name}</b>
👥 Takliflar: <b>{u['successful_invites']}</b> (2 ta = 1⭐)
⭐ Yulduzlar: <b>{format_stars(u['stars'])}</b>
👑 VIP: <b>{vip_status}</b>
🔥 Streak: {u['streak']} kun"""
        bot.send_message(m.chat.id, add_footer(text), reply_markup=markup)
    except Exception as e:
        logger.error(f"/start xatosi: {e}", exc_info=True)
        bot.send_message(m.chat.id, "❌ Kechirasiz, xatolik yuz berdi. Qaytadan urinib ko'ring.")

def delayed_claim(call, db_id, is_task=False, task_id=None, reward=None):
    time.sleep(10)
    uid = call.from_user.id
    try:
        if is_task:
            if db.complete_task(uid, task_id, reward):
                bot.send_message(call.message.chat.id, f"✅ Vazifa bajarildi! +{reward}⭐")
            else:
                bot.send_message(call.message.chat.id, "❌ Bu vazifa allaqachon bajarilgan yoki xatolik.")
        else:
            db.complete_forced(uid, db_id)
            bot.send_message(call.message.chat.id, "✅ Obuna tasdiqlandi!")
            start(call.message)
    except Exception as e:
        logger.error(f"Delayed claim xatosi: {e}")
        bot.send_message(call.message.chat.id, "❌ Xatolik yuz berdi.")

@bot.callback_query_handler(func=lambda c: True)
def callback(call):
    uid = call.from_user.id
    data = call.data
    try:
        if data.startswith("forcesub_"):
            parts = data.split("_")
            action = parts[1]
            db_id = int(parts[2])
            if action == "telegram":
                ch = db.get_forced_channels()
                target = next((c for c in ch if c[0] == db_id), None)
                if target:
                    try:
                        member = bot.get_chat_member(target[2], uid)
                        if member.status in ['member','administrator','creator']:
                            bot.answer_callback_query(call.id, "✅ Qabul qilindi!", show_alert=False)
                            try: bot.delete_message(call.message.chat.id, call.message.message_id)
                            except: pass
                            start(call.message)
                        else:
                            bot.answer_callback_query(call.id, "❌ Obuna bo'lmagansiz!", show_alert=True)
                    except:
                        bot.answer_callback_query(call.id, "❌ Tekshirib bo'lmadi!", show_alert=True)
            elif action == "claim":
                bot.answer_callback_query(call.id, "⏳ 10 soniya kutilmoqda...", show_alert=True)
                threading.Thread(target=delayed_claim, args=(call, db_id)).start()
            return

        if data == "daily":
            ok, ns, bonus, streak, extra = db.give_daily_bonus(uid)
            if ok:
                extra_text = f"\n🎉 HAFTALIK! +{extra}⭐" if extra else ""
                bot.send_message(call.message.chat.id, add_footer(f"🎁 Kunlik bonus: +{bonus}⭐\nJami: {format_stars(ns)}⭐\nStreak: {streak}{extra_text}"))
                bot.answer_callback_query(call.id, f"+{bonus}⭐", show_alert=True)
            else:
                bot.answer_callback_query(call.id, "❌ Bugun olgansiz!", show_alert=True)

        elif data == "shop":
            u = db.get(uid)
            markup = types.InlineKeyboardMarkup(row_width=2)
            for iid, item in SHOP.items():
                can = "✅" if u['stars'] >= item['price'] else "🔒"
                markup.add(types.InlineKeyboardButton(f"{can} {item['emoji']} {item['name']} {item['price']}⭐", callback_data=f"buy_{iid}"))
            bot.send_message(call.message.chat.id, add_footer(f"🛒 Balans: {format_stars(u['stars'])}⭐"), reply_markup=markup)

        elif data == "top":
            top = db.get_top(10)
            if top:
                text = "🏆 TOP 10:\n"
                for i, (top_uid, un, nm, inv, st, v, streak) in enumerate(top, 1):
                    if un:
                        user = f"@{un}"
                    elif nm:
                        user = nm
                    else:
                        user = f"ID:{top_uid}"
                    medal = "🥇" if i==1 else "🥈" if i==2 else "🥉" if i==3 else f"{i}️⃣"
                    vip = "👑" if v else ""
                    text += f"{medal} {user} {vip} - {inv} taklif, {format_stars(st)}⭐\n"
                bot.send_message(call.message.chat.id, add_footer(text))

        elif data == "profile":
            u = db.get(uid)
            vip = "✅" if u['vip'] else "❌"
            try:
                user_info = bot.get_chat(uid)
                username = f"@{user_info.username}" if user_info.username else "🚫 username yo'q"
            except: username = "🚫 username yo'q"
            bot.send_message(call.message.chat.id, add_footer(f"📊 Profil\n👤 {call.from_user.first_name}\n🆔 {uid}\n📛 {username}\n👑 VIP: {vip}\n🔥 Streak: {u['streak']}\n👥 Takliflar: {u['successful_invites']}\n⭐ Yulduz: {format_stars(u['stars'])}"))

        elif data == "link":
            link = get_invite_link(uid)
            bot.send_message(call.message.chat.id, add_footer(f"🔗 {link}"))

        elif data == "tasks":
            tasks = db.get_tasks()
            completed = db.get_user_completed_tasks(uid)
            if not tasks:
                bot.send_message(call.message.chat.id, "❌ Vazifalar yo'q")
                return
            markup = types.InlineKeyboardMarkup(row_width=1)
            for tid, ttype, ch_id, uname, name, url, reward in tasks:
                if tid in completed:
                    markup.add(types.InlineKeyboardButton(f"✅ {name}", callback_data="done"))
                else:
                    if ttype == 'telegram':
                        markup.add(types.InlineKeyboardButton(f"📢 {name} (+{reward}⭐)", url=url))
                        markup.add(types.InlineKeyboardButton("🔍 Tekshirish", callback_data=f"task_{tid}_check"))
                    else:
                        markup.add(types.InlineKeyboardButton(f"🎯 {name} (+{reward}⭐) [10s]", callback_data=f"task_{tid}_claim"))
            bot.send_message(call.message.chat.id, "✅ Vazifalar (Instagram/YouTube 10 soniya kutiladi)", reply_markup=markup)

        elif data.startswith("task_"):
            parts = data.split("_")
            if len(parts)<3: return
            tid = int(parts[1])
            action = parts[2]
            tasks = db.get_tasks()
            task = next((t for t in tasks if t[0]==tid), None)
            if not task:
                bot.answer_callback_query(call.id, "❌ Topilmadi"); return
            ttype = task[1]; ch_id = task[2]; name = task[4]; reward = task[6]
            if action == "check":
                try:
                    member = bot.get_chat_member(ch_id, uid)
                    if member.status in ['member','administrator','creator']:
                        if db.complete_task(uid, tid, reward):
                            bot.answer_callback_query(call.id, f"✅ +{reward}⭐", show_alert=True)
                            bot.send_message(call.message.chat.id, f"✅ {name} bajarildi! +{reward}⭐")
                        else:
                            bot.answer_callback_query(call.id, "❌ Bu vazifa allaqachon bajarilgan!", show_alert=True)
                    else:
                        bot.answer_callback_query(call.id, "❌ Obuna bo'lmagansiz", show_alert=True)
                except Exception as e:
                    bot.answer_callback_query(call.id, "❌ Tekshirib bo'lmadi", show_alert=True)
            elif action == "claim":
                bot.answer_callback_query(call.id, "⏳ 10 soniya kutilmoqda...", show_alert=True)
                threading.Thread(target=delayed_claim, args=(call, None, True, tid, reward)).start()

        elif data.startswith("buy_"):
            item_id = int(data.split("_")[1])
            item = SHOP.get(item_id)
            if not item: return
            u = db.get(uid)
            if u['stars'] < item['price']:
                bot.answer_callback_query(call.id, f"❌ {item['price'] - u['stars']}⭐ yetmaydi", show_alert=True)
                return
            ns = db.sub_star(uid, item['price'])
            db.add_purchase_history(uid, item['name'], item['emoji'], item['price'])
            extra = "\n👑 VIP berildi!" if item['price'] >= 50 else ""
            if item['price'] >= 50: db.grant_vip(uid)
            caption = f"""✅ <b>Sovg'a berildi!</b>

{item['emoji']} <b>{item['name']}</b>
💰 Sarflandi: <b>{item['price']}⭐</b>
⭐ Qoldi: <b>{format_stars(ns)}</b>{extra}

⏳ <b>Admin 24 soat ichida sovg'angizni yuboradi.</b>"""
            bot.send_photo(call.message.chat.id, item['photo'], caption=caption)
            bot.answer_callback_query(call.id, "✅", show_alert=True)

            # Admin xabaridagi profil havolasi
            try:
                user_info = bot.get_chat(uid)
                if user_info.username:
                    link = f"https://t.me/{user_info.username}"
                else:
                    link = f"tg://user?id={uid}"
            except:
                link = f"tg://user?id={uid}"
            markup = types.InlineKeyboardMarkup()
            markup.add(types.InlineKeyboardButton("📞 Yozish", url=link))
            admin_msg = f"🛍 {call.from_user.first_name} {item['name']} {item['price']}⭐"
            try:
                bot.send_message(ADMIN_ID, admin_msg, reply_markup=markup)
            except:
                logger.error("Admin xabari yuborilmadi. Admin botga /start bosganmi?")

        bot.answer_callback_query(call.id)
    except Exception as e:
        logger.error(f"Callback xatosi: {e}", exc_info=True)
        bot.answer_callback_query(call.id, f"❌ Xatolik: {e}", show_alert=True)

# ================= ADMIN BUYRUG'LARI =================
@bot.message_handler(commands=["admin"])
def admin_cmd(m):
    if m.from_user.id != ADMIN_ID: return
    s = db.get_stats()
    text = f"""🔐 <b>ADMIN PANEL</b>
👥 Foydalanuvchilar: {s['users']}
📊 Takliflar: {s['total_invites']}
⭐ Yulduzlar: {format_stars(s['stars'])}
👑 VIP: {s['vip']}
💸 Sarflangan: {format_stars(s['spent'])}
🛍 Xaridlar: {s['purchases']}

<b>Buyruqlar:</b>
/addstars [id] [miqdor]
/ban [id] /unban [id]
/broadcast [matn]
/addchannel [tur] [chat_id] [@] [nomi] [url]
/removetask [id] /tasklist
/search [id/username]
/userlink [id yoki @username]"""
    bot.reply_to(m, text)

@bot.message_handler(commands=["addstars"])
def addstars(m):
    if m.from_user.id != ADMIN_ID: return
    try:
        parts = m.text.split()
        if len(parts) < 3:
            bot.reply_to(m, "❌ /addstars [id] [miqdor]"); return
        uid = int(parts[1]); amount = float(parts[2])
        db.create_user(uid, None, "User")
        new_balance = db.add_stars_admin(uid, amount)
        bot.reply_to(m, f"✅ {uid} ga +{format_stars(amount)}⭐ qo'shildi. Jami: {format_stars(new_balance)}⭐")
    except Exception as e:
        bot.reply_to(m, f"❌ Xato: {e}")

@bot.message_handler(commands=["ban"])
def ban_cmd(m):
    if m.from_user.id != ADMIN_ID: return
    try:
        uid = int(m.text.split()[1])
        db.ban_user(uid)
        bot.reply_to(m, f"✅ {uid} bloklandi")
    except: bot.reply_to(m, "❌ /ban [id]")

@bot.message_handler(commands=["unban"])
def unban_cmd(m):
    if m.from_user.id != ADMIN_ID: return
    try:
        uid = int(m.text.split()[1])
        db.unban_user(uid)
        bot.reply_to(m, f"✅ {uid} blokdan chiqarildi")
    except: bot.reply_to(m, "❌ /unban [id]")

@bot.message_handler(commands=["broadcast"])
def broadcast(m):
    if m.from_user.id != ADMIN_ID: return
    try:
        text = m.text.split(maxsplit=1)[1]
        users = db.get_all_users_for_ad()
        sent = 0
        for uid in users:
            try:
                bot.send_message(uid, f"📢 {text}")
                sent += 1
                time.sleep(0.1)
            except: pass
        bot.reply_to(m, f"✅ {sent}/{len(users)}")
    except: bot.reply_to(m, "❌ /broadcast [matn]")

@bot.message_handler(commands=["addchannel"])
def addchannel(m):
    if m.from_user.id != ADMIN_ID: return
    try:
        parts = m.text.split(maxsplit=5)
        if len(parts) < 6:
            bot.reply_to(m, "❌ /addchannel [tur] [chat_id yoki 0] [@] [nomi] [url]\nMasalan:\n/addchannel telegram -100123 @kanal Kanal https://t.me/kanal")
            return
        ctype = parts[1].lower()
        if ctype not in ('telegram','instagram','youtube'):
            bot.reply_to(m, "❌ Noto'g'ri tur. telegram/instagram/youtube"); return
        ch_id = int(parts[2]); uname = parts[3]; name = parts[4]; url = parts[5]
        db.add_forced_channel(ctype, ch_id, uname, name, url)
        bot.reply_to(m, f"✅ Majburiy obuna qo'shildi: {name} ({ctype})")
    except Exception as e:
        bot.reply_to(m, f"❌ Xato: {e}")

@bot.message_handler(commands=["removetask"])
def removetask(m):
    if m.from_user.id != ADMIN_ID: return
    try:
        tid = int(m.text.split()[1])
        db.remove_task(tid)
        bot.reply_to(m, f"✅ {tid} o'chirildi")
    except: bot.reply_to(m, "❌ /removetask [id]")

@bot.message_handler(commands=["tasklist"])
def tasklist(m):
    if m.from_user.id != ADMIN_ID: return
    tasks = db.get_tasks()
    if tasks:
        text = "\n".join([f"{t[0]}: {t[1]} {t[4]} +{t[6]}⭐" for t in tasks])
        bot.reply_to(m, text)
    else: bot.reply_to(m, "Vazifalar yo'q")

@bot.message_handler(commands=["search"])
def search_cmd(m):
    if m.from_user.id != ADMIN_ID: return
    try:
        query = m.text.split(maxsplit=1)[1]
        results = db.search_user(query)
        if results:
            text = "🔍 Natijalar:\n"
            for uid, un, nm, inv, st, vip, streak in results[:10]:
                user = f"@{un}" if un else nm
                text += f"🆔{uid} {user} {'👑' if vip else ''} 👥{inv} ⭐{format_stars(st)} 🔥{streak}\n"
            bot.reply_to(m, text)
        else: bot.reply_to(m, "❌ Topilmadi!")
    except: bot.reply_to(m, "❌ /search [id/username]")

@bot.message_handler(commands=["userlink"])
def userlink_cmd(m):
    if m.from_user.id != ADMIN_ID: return
    try:
        query = m.text.split(maxsplit=1)[1]
        try: uid = int(query)
        except:
            results = db.search_user(query)
            if results: uid = results[0][0]
            else:
                bot.reply_to(m, "❌ Topilmadi!"); return
        try:
            user_info = bot.get_chat(uid)
            link = f"https://t.me/{user_info.username}" if user_info.username else f"tg://user?id={uid}"
        except: link = f"tg://user?id={uid}"
        markup = types.InlineKeyboardMarkup()
        markup.add(types.InlineKeyboardButton("🔗 Profil", url=link))
        bot.reply_to(m, f"Foydalanuvchi: {uid}", reply_markup=markup)
    except: bot.reply_to(m, "❌ /userlink [id yoki @username]")

# ================= FOYDALANUVCHI BUYRUG'LARI =================
@bot.message_handler(commands=["stats","daily","link","tasks"])
def user_cmd(m):
    uid = m.from_user.id
    cmd = m.text.split()[0][1:]
    try:
        if cmd == "stats":
            u = db.get(uid)
            total_users = db.get_stats()["users"]
            vip_status = "✅ HA" if u["vip"] else "❌ YO'Q"
            text = f"📊 <b>Sizning statistikangiz</b>\n👥 Takliflar: {u['successful_invites']}\n⭐ Yulduzlar: {format_stars(u['stars'])}\n👑 VIP: {vip_status}\n🔥 Streak: {u['streak']} kun\n\n🌐 <b>Botda jami foydalanuvchilar:</b> {total_users}"
            bot.reply_to(m, add_footer(text))
        elif cmd == "daily":
            ok, ns, bonus, streak, extra = db.give_daily_bonus(uid)
            if ok: bot.reply_to(m, add_footer(f"🎁 +{bonus}⭐ | Jami: {format_stars(ns)}⭐ | 🔥 Streak: {streak}"))
            else: bot.reply_to(m, "❌ Bugun olgansiz!")
        elif cmd == "link":
            bot.reply_to(m, f"🔗 {get_invite_link(uid)}")
        elif cmd == "tasks":
            tasks = db.get_tasks()
            if tasks:
                text = "\n".join([f"{t[4]} +{t[6]}⭐" for t in tasks])
                bot.reply_to(m, text)
            else: bot.reply_to(m, "Vazifalar yo'q")
    except Exception as e:
        bot.reply_to(m, f"❌ Xatolik: {e}")

# ================= HTTP SERVER (Port) =================
class HealthHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-type", "text/plain")
        self.end_headers()
        self.wfile.write(b"Bot ishlamoqda")
    def log_message(self, format, *args): pass

def run_http_server():
    port = int(os.environ.get("PORT", 10000))
    server = HTTPServer(("0.0.0.0", port), HealthHandler)
    print(f"🌐 HTTP server {port} portda ishga tushdi")
    server.serve_forever()

# ================= ISHGA TUSHIRISH =================
if __name__ == "__main__":
    print("🚀 Bot ishga tushirilmoqda (Web Service)...")
    try:
        resp = requests.get(f"https://api.telegram.org/bot{API_TOKEN}/getMe", timeout=10)
        if resp.status_code != 200 or not resp.json().get("ok"):
            print("❌ Token noto'g'ri!"); exit(1)
        print(f"✅ Token to'g'ri: @{resp.json()['result']['username']}")
    except Exception as e:
        print(f"❌ Token tekshirib bo'lmadi: {e}"); exit(1)
    for _ in range(3):
        try:
            requests.get(f"https://api.telegram.org/bot{API_TOKEN}/deleteWebhook?drop_pending_updates=true", timeout=5)
            break
        except: time.sleep(2)
    threading.Thread(target=run_http_server, daemon=True).start()
    time.sleep(2)
    while True:
        try:
            bot.infinity_polling(timeout=60, skip_pending=True)
        except KeyboardInterrupt: break
        except Exception as e:
            logger.error(f"Polling xatosi: {e}"); time.sleep(5)
